// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfpragtmujequuwcnorj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmcHJhZ3RtdWplcXV1d2Nub3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5ODk0NTgsImV4cCI6MjA1NTU2NTQ1OH0.L-24E7W9CLL_87AjXPYyF-vJFRoFFwn6fKJZrwZPgJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);